spring.application.name=marketplace-core
# database source
spring.datasource.url=jdbc:oracle:thin:@//oracle-enterprise:1521/FREEPDB1
spring.datasource.username=SYSTEM
spring.datasource.password=admin123
# flyaway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# logging
logging.level.root=INFO
logging.level.com.example.marketplace=INFO

# Never enable sensitive request details globally.
spring.mvc.log-request-details=false