spring.application.name=core
spring.datasource.url=jdbc:oracle:thin:@//oracle-enterprise:1521/FREEPDB1
spring.datasource.username=SYSTEM
spring.datasource.password=admin123

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
