plugins {
    id 'org.springframework.boot' version '4.1.1' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
    id 'com.github.spotbugs' version '6.5.11' apply false
}

allprojects {
    group = 'com.example'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'checkstyle'
    apply plugin: 'pmd'
    apply plugin: 'com.github.spotbugs'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    // checkstyle
    checkstyle {
        toolVersion = '13.4.2'
        configFile = rootProject.file("config/checkstyle/checkstyle.xml")
        maxWarnings = 0
        ignoreFailures = false
    }

    // pmd
    pmd {
        toolVersion = '7.27.0'
        ruleSetFiles = files(rootProject.file("config/pmd/ruleset.xml"))
        ruleSets = []
        ignoreFailures = false
    }

    // spotbugs
    spotbugs {
        ignoreFailures = false
        effort = 'max'
        reportLevel = 'high'
    }

    tasks.withType(Checkstyle).configureEach {
        reports {
            xml.required = true
            html.required = true
        }
    }

    tasks.withType(Pmd).configureEach {
        reports {
            xml.required = true
            html.required = true
        }
    }

    tasks.withType(com.github.spotbugs.snom.SpotBugsTask).configureEach {
        reports {
            create("xml") { required = true }
            create("html") { required = true }
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()

        testLogging {
            events "failed"
            exceptionFormat "full"
            showExceptions true
            showCauses true
            showStackTraces true
        }
    }
}