CREATE TABLE webhook_inbox (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR2(100) NOT NULL,
  event_id VARCHAR2(255) NOT NULL,
  payload CLOB NOT NULL,
  received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  processed_at TIMESTAMP NULL,
  CONSTRAINT uq_webhook_inbox_provider_event UNIQUE (provider, event_id)
);
