name: Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t marketplace-service ./backend/marketplace-service
      - run: docker build -t marketplace-web ./frontend/web
